// Urutan kelas disesuaikan dengan urutan folder dataset (Python sorted())
export const HIJAIYAH_CLASSES = [
  "0_alif",
  "10_zai",
  "11_sin",
  "12_syin",
  "13_sho",
  "14_dho",
  "15_tho",
  "16_zho",
  "17_ain",
  "18_ghain",
  "19_fa",
  "1_ba",
  "20_qof",
  "21_kaf",
  "22_lam",
  "23_mim",
  "24_nun",
  "25_wau",
  "26_Ha",
  "27_ya",
  "2_ta",
  "3_tsa",
  "4_jim",
  "5_ha",
  "6_kho",
  "7_dal",
  "8_dzal",
  "9_ro"
];

// Pemetaan label key ke teks tampilan Bahasa Indonesia
export const HIJAIYAH_LABELS: Record<string, string> = {
  "0_alif": "Alif (ا)",
  "1_ba": "Ba (ب)",
  "2_ta": "Ta (ت)",
  "3_tsa": "Tsa (ث)",
  "4_jim": "Jim (ج)",
  "5_ha": "Ha (ح)",
  "6_kho": "Kho (خ)",
  "7_dal": "Dal (د)",
  "8_dzal": "Dzal (ذ)",
  "9_ro": "Ro (ر)",
  "10_zai": "Zai (ز)",
  "11_sin": "Sin (س)",
  "12_syin": "Syin (ش)",
  "13_sho": "Shod (ص)",
  "14_dho": "Dhod (ض)",
  "15_tho": "Tho (ط)",
  "16_zho": "Zho (ظ)",
  "17_ain": "Ain (ع)",
  "18_ghain": "Ghain (غ)",
  "19_fa": "Fa (ف)",
  "20_qof": "Qof (ق)",
  "21_kaf": "Kaf (ك)",
  "22_lam": "Lam (ل)",
  "23_mim": "Mim (م)",
  "24_nun": "Nun (ن)",
  "25_wau": "Wau (و)",
  "26_Ha": "Ha (هـ)",
  "27_ya": "Ya (ي)",
};